<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>title</th>
        <th>rate</th>
        <th>action</th>
    </tr>
    <?php foreach ($books as $book) /** @var \Booklist\Model\Books $book */ { ?>
        <tr>
            <td style="max-width: 30em">
                <a href="/books/<?= $book->getId() ?>/detail">
                    <?= $book->getTitle() ?>
                </a>
            </td>
            <td><?= $book->getRate() ?></td>
            <td>
                <button type="button" class="btn btn-default"
                        onclick="location.href='/books/<?= $book->getId() ?>/rate/plus'">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
                <button type="button" class="btn btn-default"
                        onclick="location.href='/books/<?= $book->getId() ?>/rate/minus'">
                    <span class="glyphicon glyphicon-minus"></span>
                </button>
            </td>
        </tr>
    <?php } // endforeach ?>
</table>