<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>title</th>
        <th>rate</th>
        <th>action</th>
    </tr>
    <?php foreach ($books as $book) /** @var \Booklist\Model\Books $book */ { ?>
        <tr>
            <td style="max-width: 30em">
                <a href="<?= rtrim(base_uri(), '/') ?>/books/<?= h($book->getId()) ?>/detail">
                    <?= h($book->getTitle()) ?>
                </a>
            </td>
            <td><?= h($book->getRate()) ?></td>
            <td>
                <?php if (!$book->isModifiedToday()) { ?>
                    <button type="button" class="btn btn-default"
                            onclick="location.href='<?= rtrim(base_uri(), '/') ?>/books/<?= h($book->getId()) ?>/rate/plus'">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
                    <button type="button" class="btn btn-default"
                            onclick="location.href='<?= rtrim(base_uri(), '/') ?>/books/<?= h($book->getId()) ?>/rate/minus'">
                        <span class="glyphicon glyphicon-minus"></span>
                    </button>
                <?php } // endif ?>
                <button type="button" class="btn btn-default"
                        onclick="if(confirm('Are you sure?'))location.href='<?= rtrim(base_uri(), '/') ?>/books/<?= h($book->getId()) ?>/delete'">
                    <span class="glyphicon glyphicon-remove"></span>
                </button>
            </td>
        </tr>
    <?php } // endforeach ?>
</table>