<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?= get_base_uri(true) ?>/bootstrap/css/bootstrap.min.css">
    <title>Book List</title>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <!--<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">-->
            <!--    <span class="sr-only">foo</span>-->
            <!--    <span class="icon-bar">bar</span>-->
            <!--    <span class="icon-bar">baz</span>-->
            <!--    <span class="icon-bar"></span>-->
            <!--</button>-->
            <a class="navbar-brand" href="/">Book List</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="/books/new">New Book</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container" style="margin-top: 5em">
    <?= $this->getContent() ?>
</div>
<script type="text/javascript" src="<?= get_base_uri(true) ?>/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>
