<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?= rtrim(base_uri(), '/') ?>/bootstrap/css/bootstrap.min.css">
    <title>Book List</title>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="<?= base_uri() ?>">Book List</a>
        </div>
        <div class="navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?= base_uri() ?>">Home</a></li>
                <li><a href="<?= rtrim(base_uri(), '/') ?>/books/new">New Book</a></li>
                <li>
                    <form action="<?= rtrim(base_uri(), '/') ?>" class="navbar-form navbar-right">
                        <div class="form-group">
                            <div class="form-group">
                                <input type="text" placeholder="Search" class="form-control" name="search">
                            </div>
                            <button type="submit" class="btn btn-info">Search</button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="container" style="margin-top: 5em">
    <?= $this->getContent() ?>
</div>
<script type="text/javascript" src="<?= rtrim(base_uri(), '/') ?>/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>
